### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by biapar** [jamesmontemagno/mvvm-helpers#65]
Is there any documentation?

**Comment by jamesmontemagno** [comment]
Everything is on the readme.. Anything specific you are looking for?

**Comment by biapar** [comment]
Which are the advantages respect standard MVVM Xamarin?

**Comment by jamesmontemagno** [comment]
These are just helpers that build on top of standard MVVM with Xamarin apps. For example you can use AsyncCommand when you have a method that is Task based. You can use ObservableObject or BaseViewModel instead of implementing INotifyPropertyChanged or standard properties. Using ObservableRangeCollection over ObservableCollection lets you add and update ranges instead of adding and removing single objects. Just nice things to use.
