### ISSUE TITLE
RaisePropertyCanChange doesnot work

### ISSUE THREAD

**Issue by eduardoagr** [jamesmontemagno/mvvm-helpers#89]
Hello everyone, this is an amazing plug-in, but I found that I cannot enable/disable a button based on the input 

```
public class MainWindowViewModel : BaseViewModel
{
    public Command? MyProperty
    {
        get; set;
    }
    public AirportServices Services
    {
        get; set;
    }

    public ObservableCollection<Airport> AirportsList
    {
        get; set;
    }

    public Airport? SelectedItem
    {
        get; set;
    }

    public MainWindowViewModel()
    {
        Services = new AirportServices();

        AirportsList = new ObservableCollection<Airport>();

        MyProperty = new Command(doStu1ff,caDo);
        PropertyChanged += (_,_) => MyProperty.RaiseCanExecuteChanged();
    }

    private void doStu1ff(object obj)
    {
        MessageBox.Show("Hello");
    }
    private bool caDo(object arg)
    {
        if (!string.IsNullOrEmpty(SelectedItem?.name))
        {
            return true;

        }

        return false;
    }

```

In my Ui I have

```
<TextBox Text="{Binding SelectedItem.name}"/>

            <Button Grid.Column="1" Grid.Row="2" Content="cccccccccccc" Background="#FF265E6D" Command="{Binding MyProperty}"/>
```

It doesn't enable the button when I type something

**Comment by nedmech** [comment]
I haven't used this library directly, but looked at parts of it as inspiration to roll my own. Looking at the source code and unit tests for this library, I'm pretty sure you need to call SetProperty in your property setters to get them to broadcast a PropertyChanged event that would trigger your handler that calls the RaiseCanExecuteChanged method. Also, does your Airport class also implement BaseViewModel/INotifyPropertyChanged? The Airport.name property (or is it just a field?) would need to emit a PropertyChanged event as well, and I think you'd have to set-up/tear-down a weak-event-listener to listen for the SelectedItem.name change as the SelectedItem changes.

Instead, I might suggest wrapping the SelectedItem.name in a SelectedItemName property to make the event handling easier:

```
private Airport? _selectedItem;
public Airport? SelectedItem
{
    get => _selectedItem;
    set
    {
        SetProperty(ref _selectedItem, value);
        // Broadcast that the SelectedItemName should now have a new value as well.
        OnPropertyChanged(nameof(SelectedItemName);
        // Broadcast that the command's CanExecute should be re-evaluated now.
        MyProperty.RaiseCanExecuteChanged();
    }
}

SelectedItemName // Bind this to your TextBox.Text instead
{
    get => SelectedItem?.name ?? string.Empty;
    set
    {
        if (null == SelectedItem)
        {
            // Can't set the value if no item is selected.
            // Broadcast the changed event to refresh the binding (will be empty string).
            // This effectively rejects typing in the box until an item is selected.
            OnPropertyChanged();
            return;
        }
        SetProperty(ref SelectedItem.name, value); // Note: this may only work if Airport.name is a field, not a property.
        /* If Airport.name is a property, do this instead:
        SelectedItem.name = value;
        OnPropertyChanged(); // Broadcast that this property (SelectedItemName) has a new value.
        */
        // Broadcast that the command's CanExecute should be re-evaluated now.
        MyProperty.RaiseCanExecuteChanged();
    }
```
This way you can drop the anonymous PropertyChanged event delegate from your constructor altogether.

Also, you probably don't need the public setters for your `MyProperty`, `Services`, or `AirportsList` properties - typically nothing outside of this class should probably be setting those.

You might want to add `UpdateSourceTrigger=PropertyChanged` to your TextBox.Text binding as well so it updates as you type instead of the default behavior of only updating after the focus changes (unless that's the behavior you want).

Hope this helps, and if it's still having an issue, maybe there really is an issue with the library. Although I suspect this should address your problem.

**Comment by eduardoagr** [comment]
Thanks, @nedmech, I have a question, if I am using fody to inject my property change, Do I still need

```
private Airport? _selectedItem;
public Airport? SelectedItem
{
    get => _selectedItem;
    set
    {
        SetProperty(ref _selectedItem, value);
        // Broadcast that the SelectedItemName should now have a new value as well.
        OnPropertyChanged(nameof(SelectedItemName);
        // Broadcast that the command's CanExecute should be re-evaluated now.
        MyProperty.RaiseCanExecuteChanged();
    }
}

```
As far as I know, when you add fody and put in your class [addNotifyPropertyChangeInterface] it will add all that code for you  you only need to do is

```
public Airport SelectedItem { get; set }
```
Also my class has the [AdNotyfyProertyChangeAtribute] courtesy of fody

**Comment by nedmech** [comment]
I haven't used fody before, so I'm not familiar with the usage. A quick peek at it seems like you're probably correct - it should be auto-generating the code for notifying that the selected item has changed. Although there's still the question of whether or not the Airport.name is a field or property and if the Airport class implements INotifyPropertyChanged. Even if your Airport.name is a notifying property, there's still a missing connection between the SelectedItem.name changing and triggering the RaiseCanExecuteChanged. Without a weak-event-listener or wrapping it in another property, there's nothing in your MainWindowViewModel that is listening for change notifications from the Airport.name value.

Try it with just the SelectedItemName property wrapper and see what happens. My guess is that typing in a name will trigger the CanExecute update, but just selecting an item won't. Maybe some combination of my idea and your original code where you subscribed to the PropertyChanged event will work since you should get the PropertyChanged event when the SelectedItem changes and when the SelectedItemName is updated. You can probably exclude the RaiseCanExecuteChanged from the SelectedItemName setter in this case.

**Comment by eduardoagr** [comment]
I did it, but there is a small issue

the button only enables, when I press the tab, to make it loses focus, what I want to do is that when I type the button enables infinitely, without me having to change the control focus or anything like that.

I just my code in GitHub, if you want to check it out or modify it or whatever

https://github.com/eduardoagr/Travel

By the way, this library in combination with fody is extraordinary

**Comment by nedmech** [comment]
To get the changes to register immediately when typing in the TextBox, you need to add the UpdateSourceTrigger attribute I mentioned before to the TextBox.Text binding:
```
<TextBox Grid.Column="1" Text="{Binding Path=SelectedItem.name, UpdateSourceTrigger=PropertyChanged}"/>
```
This should cause the PropertyChanged event for the name property to fire with every keystroke.

Does the button enabled when you select an Airport item that already has a name? You may still need to add a RaiseCanExectuteChanged to the setter for the SelectedItem, or another PropertyChanged event delegate to handle refreshing the CanExecute status on selection change.

In your constructor, I think you've got a problem with the OnAnyPropertiesChanged action assignment:
```
        SelectedItem = new Airport
        {
            OnAnyPropertiesChanged = () => { MyProperty?.RaiseCanExecuteChanged(); }
        };
```
I think this will only attach to the new instance of Airport that gets created in the constructor. If you've got your AirportList and SelectedItem bound to a selectable control (ListBox, ListView, ComboBox, etc.) when you actually select a new Airport from your collection, the SelectedItem will be replaced by the selection, and that newly selected item doesn't look like it will have the OnAnyPropertiesChanged action assigned. It doesn't look like your code is completed to that point yet, but just something to be aware of.

But it sounds like you're on the right track and that there's not an issue with the library, just some tweaks needed to your implementation.

**Comment by eduardoagr** [comment]
I changed my code, but I still cannot manage to enable it as I type

**Comment by nedmech** [comment]
It looks like you added the UpdateSourceTrigger attribute to the Button.Command binding. It belongs on the TextBox.Text binding.

**Comment by eduardoagr** [comment]
lol, thanks so much
